# Generated by Django 6.1.1 on 2026-09-25 12:48

import django.db.models.deletion
import medical_records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_doctoravailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_observations', models.TextField(help_text='Objective clinical observations and consultation summary.')),
                ('follow_up_instructions', models.TextField(blank=True, help_text='Recommended lifestyle guidance, tests, or follow-up directions.')),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended follow-up date if applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_note', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='doctors.doctorprofile')),
            ],
            options={
                'verbose_name': 'Consultation Note',
                'verbose_name_plural': 'Consultation Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('IMAGING', 'Imaging / X-Ray / Scan'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('INSURANCE', 'Insurance Document'), ('OTHER', 'Other Medical Document')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=medical_records.models.patient_document_upload_path)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Optional appointment this document relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='appointments.appointment')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Document',
                'verbose_name_plural': 'Medical Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
