# Generated by Django 6.1.1 on 2026-09-22 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(help_text='Primary medical specialization (e.g. Cardiology, Neurology, General Medicine).', max_length=100)),
                ('qualification', models.CharField(help_text='Educational qualifications (e.g. MBBS, MD, MS, FRCS).', max_length=150)),
                ('license_number', models.CharField(help_text='Medical council license/registration number.', max_length=50, unique=True)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of clinical medical practice.')),
                ('bio', models.TextField(blank=True, help_text='Professional clinical summary and background.')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard consultation fee in local currency.', max_digits=10)),
                ('profile_photo', models.ImageField(blank=True, help_text='Doctor professional headshot.', null=True, upload_to='doctors/photos/')),
                ('is_approved', models.BooleanField(default=False, help_text='Verification approval status by MediConnect administrator.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The associated user account.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
    ]
