# Generated by Django 6.1.1 on 2026-09-25 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_REJECTED', 'Appointment Rejected'), ('APPOINTMENT_COMPLETED', 'Appointment Completed'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('DOCTOR_APPROVED', 'Doctor Approved'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('GENERAL', 'General Information')], default='GENERAL', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_appointment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='Recipient user of this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
